/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lendle.courses.wp.dialogsample;

import javax.swing.JOptionPane;

/**
 *
 * @author lendle
 */
public class ShowMessageDialogSample extends javax.swing.JFrame {

    /**
     * Creates new form ShowMessageDialogSample
     */
    public ShowMessageDialogSample() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        defaultbutton = new javax.swing.JButton();
        errorbutton = new javax.swing.JButton();
        informationbutton = new javax.swing.JButton();
        plainbutton = new javax.swing.JButton();
        questionbutton = new javax.swing.JButton();
        warningbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(6, 1));

        defaultbutton.setText("Default");
        defaultbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                defaultbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(defaultbutton);

        errorbutton.setText("Error");
        errorbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                errorbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(errorbutton);

        informationbutton.setText("Information");
        informationbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                informationbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(informationbutton);

        plainbutton.setText("Plain");
        plainbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plainbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(plainbutton);

        questionbutton.setText("Question");
        questionbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                questionbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(questionbutton);

        warningbutton.setText("Warning");
        warningbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                warningbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(warningbutton);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void defaultbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_defaultbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_defaultbuttonActionPerformed

    private void errorbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_errorbuttonActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "hello", "", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_errorbuttonActionPerformed

    private void informationbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_informationbuttonActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "hello", "", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_informationbuttonActionPerformed

    private void plainbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plainbuttonActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "hello", "", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_plainbuttonActionPerformed

    private void questionbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_questionbuttonActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "hello", "", JOptionPane.QUESTION_MESSAGE);
    }//GEN-LAST:event_questionbuttonActionPerformed

    private void warningbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_warningbuttonActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "hello", "", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_warningbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowMessageDialogSample.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowMessageDialogSample.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowMessageDialogSample.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowMessageDialogSample.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowMessageDialogSample().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton defaultbutton;
    private javax.swing.JButton errorbutton;
    private javax.swing.JButton informationbutton;
    private javax.swing.JButton plainbutton;
    private javax.swing.JButton questionbutton;
    private javax.swing.JButton warningbutton;
    // End of variables declaration//GEN-END:variables
}
